### ISSUE TITLE
Experiment by adding notebook as chapter

### ISSUE THREAD

**Issue by erinmr** [NASA-Openscapes/openscapes_jupyterbook_test#6]
It would be great to see how a notebook looks/interacts in the JupyterBook.

**Comment by erinmr** [comment]
These notebooks from @amfriesz might be good additions to the book -> [https://github.com/amfriesz/eros_cop_webinar_notebooks](https://github.com/amfriesz/eros_cop_webinar_notebooks)

**Comment by jules32** [comment]
Nice job @cpkrehbiel adding a [jupyter notebook today](https://nasa-openscapes.github.io/openscapes_jupyterbook_test/discovery/Navigate_CMR_STAC.html). 

Located [here on GitHub[(https://github.com/NASA-Openscapes/openscapes_jupyterbook_test/blob/master/book/discovery/Navigate_CMR_STAC.ipynb)

**Comment by jules32** [comment]
> These notebooks from @amfriesz might be good additions to the book -> https://github.com/amfriesz/eros_cop_webinar_notebooks

@amfriesz would you have a look at those and if they are good candidates to move to the book we can work on that. Otherwise we can close this issue :)

**Comment by amfriesz** [comment]
I think they would be good to add, but with some refinements. There is a lot of cross-over with the HLS tutorial. I'm looking into that now.
