### ISSUE TITLE
Add PO.DAAC Cloud intro

### ISSUE THREAD

**Issue by erinmr** [NASA-Openscapes/openscapes_jupyterbook_test#7]
Would be great to use PO.DAAC Cloud Intro from their [website](https://podaac.jpl.nasa.gov/cloud-datasets/about). Catalina shared images for the book.

**Comment by erinmr** [comment]
![cloud_paradigm_Earthdata](https://user-images.githubusercontent.com/2915555/119879459-8059f000-bee8-11eb-80c6-05723c92ff14.png)

**Comment by jules32** [comment]
Added @ScienceCat18 's image and borrowed some of the text from the [PODAAC's Cloud Data](https://podaac.jpl.nasa.gov/cloud-datasets/about). We can discuss more how much we can reuse here and how to credit :)

https://nasa-openscapes.github.io/openscapes_jupyterbook_test/
